services:
  frontend:
    image: recipe-book/frontend:${FRONTEND_VERSION}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  backend:
    image: recipe-book/backend:${BACKEND_VERSION}
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@database:3306/${DATABASE_DATABASE}

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASE}
    ports:
      - "13306:3306"
    volumes:
      - recipeBook_data:/var/lib/mysql

volumes:
  recipeBook_data:
